import { useState } from 'react';
import type { AssessmentResult, RecordedIntervention } from '@neonatal/clinical-domain';
import { saveInterventions } from '../../api/client';
import { ClinicalButton } from '../../components/ClinicalButton';
import { RecommendationPanel } from '../../components/RecommendationPanel';

export function InterventionRecorder({encounterId,result,onSaved}:{encounterId:string;result:AssessmentResult;onSaved:(items:RecordedIntervention[])=>void}){
  const [selected,setSelected]=useState<string[]>([]);const [medication,setMedication]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
  const toggle=(id:string)=>setSelected(prev=>prev.includes(id)?prev.filter(x=>x!==id):[...prev,id]);
  const save=async()=>{setLoading(true);setError('');try{const nonMedication=result.recommendation.nonMedication.filter(action=>selected.includes(action.id)).map(action=>({actionId:action.id,labelFa:action.labelFa,kind:'non-medication' as const}));const medicationItem=medication&&result.recommendation.medication?[{actionId:'physician-ordered-medication',labelFa:'مداخله دارویی طبق تجویز پزشک',kind:'physician-ordered-medication' as const}]:[];const response=await saveInterventions(encounterId,[...nonMedication,...medicationItem]);onSaved(response.interventions);}catch(error:any){setError(error?.message??'ثبت مداخله انجام نشد.');}finally{setLoading(false)}};
  return <section className="intervention-stack"><RecommendationPanel result={result}/><div className="clinical-card"><div className="section-heading"><div><span className="eyebrow">ثبت اقدام انجام‌شده</span><h2>کدام مداخلات واقعاً انجام شدند؟</h2><p>توصیه‌های غیردارویی بالاتر همیشه قابل مشاهده‌اند. در این بخش فقط موارد انجام‌شده را برای گزارش ثبت کنید.</p></div></div><div className="performed-grid">{result.recommendation.nonMedication.map(action=><label className="performed-card" key={action.id}><input type="checkbox" checked={selected.includes(action.id)} onChange={()=>toggle(action.id)}/><span><strong>{action.labelFa}</strong><small>مداخله غیردارویی</small></span></label>)}</div>{result.recommendation.medication?<label className="performed-card performed-card--medical"><input type="checkbox" checked={medication} onChange={e=>setMedication(e.target.checked)}/><span><strong>مداخله دارویی طبق تجویز پزشک انجام شد</strong><small>این ثبت به معنی صدور دستور دارویی توسط سامانه نیست.</small></span></label>:null}{error?<div className="inline-error" role="alert">{error}</div>:null}<div className="form-actions"><ClinicalButton onClick={save} loading={loading} showArrow>ثبت مداخلات و ادامه</ClinicalButton></div></div></section>
}
