import { useMemo, useState, type CSSProperties } from 'react';
import type { AssessmentResult, InfantContext } from '@neonatal/clinical-domain';
import { SCALE_DEFINITIONS } from '@neonatal/clinical-domain';
import { evaluateAssessment } from '../../api/client';
import { AlertIcon } from '../../components/icons';
import { ClinicalButton } from '../../components/ClinicalButton';
import { RecommendationPanel } from '../../components/RecommendationPanel';

const pippGaFromWeeks=(weeks?:number)=>weeks===undefined?null:weeks>=36?0:weeks>=32?1:weeks>=28?2:3;
const percentScore=(value:number)=>value<=9?0:value<=39?1:value<=69?2:3;
const percentCategory=(value:number)=>value<=9?'۰–۹٪ زمان':value<=39?'۱۰–۳۹٪ زمان':value<=69?'۴۰–۶۹٪ زمان':'۷۰–۱۰۰٪ زمان';

function PercentageSlider({id,label,value,touched,onChange,onTouch,disabled=false}:{id:string;label:string;value:number;touched:boolean;onChange:(value:number)=>void;onTouch:()=>void;disabled?:boolean}){
  const score=percentScore(value);const category=percentCategory(value);
  return <fieldset className={`range-card ${touched?'is-answered':''}`}><legend>{label}</legend><div className="range-head"><span>{category}</span><strong>امتیاز {score}</strong></div><div className="range-shell" style={{'--range-value':`${value}%`} as CSSProperties}><output htmlFor={id}>{value}٪</output><input id={id} type="range" min={0} max={100} step={1} value={value} disabled={disabled} aria-label={`${label}؛ درصد زمان`} aria-valuetext={`${value} درصد؛ ${category}؛ امتیاز ${score}`} onPointerDown={onTouch} onKeyDown={event=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End','PageUp','PageDown'].includes(event.key))onTouch()}} onChange={event=>{onTouch();onChange(Number(event.target.value))}}/><div className="range-thresholds" aria-hidden="true"><span>۰</span><span style={{left:'10%'}}>۱۰</span><span style={{left:'40%'}}>۴۰</span><span style={{left:'70%'}}>۷۰</span><span style={{left:'100%'}}>۱۰۰٪</span></div></div>{!touched?<small className="range-pending">برای ثبت این معیار، مقدار را روی اسلایدر تأیید یا تغییر دهید.</small>:null}</fieldset>
}

export function PippAssessment({infantContext,encounterId,onResult,onContinue,continueLabel='ادامه به مداخله'}:{infantContext?:InfantContext;encounterId?:string;onResult?:(result:AssessmentResult)=>void;onContinue?:(result:AssessmentResult)=>void;continueLabel?:string}){
  const definition=SCALE_DEFINITIONS.PIPP;
  const gaItem=definition.items.find(item=>item.id==='ga')!;const behaviorItem=definition.items.find(item=>item.id==='behavior')!;
  const [gaScore,setGaScore]=useState<number>();const [behavior,setBehavior]=useState<number>();
  const [baselineHr,setBaselineHr]=useState('');const [baselineSpo2,setBaselineSpo2]=useState('');const [baselineConfirmed,setBaselineConfirmed]=useState(false);const [procedureConfirmed,setProcedureConfirmed]=useState(false);
  const [maxHr,setMaxHr]=useState('');const [minSpo2,setMinSpo2]=useState('');
  const [percent,setPercent]=useState({brow:0,eye:0,nasolabial:0});const [touched,setTouched]=useState({brow:false,eye:false,nasolabial:false});
  const [result,setResult]=useState<AssessmentResult>();const [loading,setLoading]=useState(false);const [error,setError]=useState('');
  const expectedGa=pippGaFromWeeks(infantContext?.gestationalWeeks);const mismatch=gaScore!==undefined&&expectedGa!==null&&gaScore!==expectedGa;
  const baselineReady=gaScore!==undefined&&behavior!==undefined&&Number(baselineHr)>0&&Number(baselineSpo2)>=0&&Number(baselineSpo2)<=100;
  const postReady=baselineConfirmed&&procedureConfirmed&&Number(maxHr)>0&&Number(minSpo2)>=0&&Number(minSpo2)<=100&&Object.values(touched).every(Boolean);
  const completed=useMemo(()=>[gaScore,behavior,baselineHr?1:undefined,baselineSpo2?1:undefined,maxHr?1:undefined,minSpo2?1:undefined,...Object.values(touched).map(Boolean)].filter(Boolean).length,[gaScore,behavior,baselineHr,baselineSpo2,maxHr,minSpo2,touched]);
  const evaluate=async()=>{if(!postReady||gaScore===undefined||behavior===undefined)return;setLoading(true);setError('');try{const next=await evaluateAssessment({scale:'PIPP',encounterId,infantContext,answers:{gaScore,behavior,baselineHr:Number(baselineHr),baselineSpo2:Number(baselineSpo2),maxHr:Number(maxHr),minSpo2:Number(minSpo2),browPercent:percent.brow,eyePercent:percent.eye,nasolabialPercent:percent.nasolabial}});setResult(next);onResult?.(next);}catch(error:any){setError(error?.message??'ارتباط با API برقرار نشد. مقادیر واردشده حفظ شده‌اند.');}finally{setLoading(false)}};
  return <section className="assessment-stack pipp-assessment"><header className="assessment-heading"><div><span className="eyebrow">PIPP</span><h2>{definition.title}</h2><p>ثبت مرحله‌ای خط پایه، اقدام و پاسخ بلافاصله پس از اقدام.</p></div><span className="scale-pill">۷ شاخص · حداکثر ۲۱</span></header>
    <section className={`pipp-stage ${baselineConfirmed?'is-complete':''}`}><header><span className="stage-number">۱</span><div><h3>خط پایه پیش از اقدام</h3><p>HR، SpO₂، سن حاملگی PIPP و رفتار را ثبت کنید.</p></div><span className="stage-state">{baselineConfirmed?'ثبت شد':'در انتظار ثبت'}</span></header><div className="pipp-stage__body">
      <fieldset className="criterion-card compact"><legend>سن حاملگی در PIPP</legend><div className="option-grid">{gaItem.options.map(option=><label className="option-tile" key={option.value}><input type="radio" name="pipp-ga" checked={gaScore===option.value} onChange={()=>{setGaScore(option.value);setBaselineConfirmed(false);setResult(undefined)}}/><span className="option-tile__copy"><strong>{option.labelFa}</strong><small>امتیاز {option.value}</small></span></label>)}</div></fieldset>
      {mismatch&&!result?<div className="mismatch-warning" role="status"><AlertIcon/><div><strong>هشدار ناسازگاری سن حاملگی</strong><span>در اطلاعات اولیه {infantContext?.gestationalWeeks} هفته ثبت شده است، اما دسته انتخاب‌شده در PIPP با آن متفاوت است. انتخاب شما حفظ می‌شود و این هشدار مانع ادامه نیست.</span></div></div>:null}
      <fieldset className="criterion-card compact"><legend>وضعیت رفتاری</legend><div className="option-grid">{behaviorItem.options.map(option=><label className="option-tile" key={option.value}><input type="radio" name="pipp-behavior" checked={behavior===option.value} onChange={()=>{setBehavior(option.value);setBaselineConfirmed(false);setResult(undefined)}}/><span className="option-tile__copy"><strong>{option.labelFa}</strong><small>امتیاز {option.value}</small></span></label>)}</div></fieldset>
      <div className="metric-grid"><label className="field"><span>HR خط پایه</span><div className="unit-input"><input type="number" min={0} value={baselineHr} onChange={e=>{setBaselineHr(e.target.value);setBaselineConfirmed(false)}}/><span>bpm</span></div></label><label className="field"><span>SpO₂ خط پایه</span><div className="unit-input"><input type="number" min={0} max={100} step="0.1" value={baselineSpo2} onChange={e=>{setBaselineSpo2(e.target.value);setBaselineConfirmed(false)}}/><span>%</span></div></label></div>
      <ClinicalButton disabled={!baselineReady||baselineConfirmed} success={baselineConfirmed} onClick={()=>setBaselineConfirmed(true)}>{baselineConfirmed?'خط پایه ثبت شد':'ثبت خط پایه و ادامه'}</ClinicalButton>
    </div></section>
    <section className={`pipp-stage ${!baselineConfirmed?'is-locked':''} ${procedureConfirmed?'is-complete':''}`} aria-disabled={!baselineConfirmed}><header><span className="stage-number">۲</span><div><h3>ثبت اقدام</h3><p>انجام اقدام دردناک / درمانی را تأیید کنید.</p></div><span className="stage-state">{procedureConfirmed?'ثبت شد':baselineConfirmed?'آماده':'قفل'}</span></header><div className="pipp-stage__body"><label className="confirm-card"><input type="checkbox" disabled={!baselineConfirmed} checked={procedureConfirmed} onChange={e=>{setProcedureConfirmed(e.target.checked);setResult(undefined)}}/><span>اقدام دردناک / درمانی انجام شد.</span></label></div></section>
    <section className={`pipp-stage ${!baselineConfirmed||!procedureConfirmed?'is-locked':''}`} aria-disabled={!baselineConfirmed||!procedureConfirmed}><header><span className="stage-number">۳</span><div><h3>ارزیابی بلافاصله پس از اقدام</h3><p>بیشترین HR، کمترین SpO₂ و درصد مشاهده علائم چهره را ثبت کنید.</p></div><span className="stage-state">{postReady?'آماده محاسبه':'در انتظار تکمیل'}</span></header><div className="pipp-stage__body">
      <div className="metric-grid"><label className="field"><span>بیشترین HR</span><div className="unit-input"><input type="number" min={0} disabled={!procedureConfirmed} value={maxHr} onChange={e=>{setMaxHr(e.target.value);setResult(undefined)}}/><span>bpm</span></div></label><label className="field"><span>کمترین SpO₂</span><div className="unit-input"><input type="number" min={0} max={100} step="0.1" disabled={!procedureConfirmed} value={minSpo2} onChange={e=>{setMinSpo2(e.target.value);setResult(undefined)}}/><span>%</span></div></label></div>
      <PercentageSlider disabled={!procedureConfirmed} id="pipp-brow" label="درهم کشیدن ابروها" value={percent.brow} touched={touched.brow} onTouch={()=>setTouched(prev=>({...prev,brow:true}))} onChange={value=>{setPercent(prev=>({...prev,brow:value}));setResult(undefined)}}/>
      <PercentageSlider disabled={!procedureConfirmed} id="pipp-eye" label="فشردن چشم‌ها" value={percent.eye} touched={touched.eye} onTouch={()=>setTouched(prev=>({...prev,eye:true}))} onChange={value=>{setPercent(prev=>({...prev,eye:value}));setResult(undefined)}}/>
      <PercentageSlider disabled={!procedureConfirmed} id="pipp-nasolabial" label="خط کنار پره‌های بینی" value={percent.nasolabial} touched={touched.nasolabial} onTouch={()=>setTouched(prev=>({...prev,nasolabial:true}))} onChange={value=>{setPercent(prev=>({...prev,nasolabial:value}));setResult(undefined)}}/>
      {error?<div className="inline-error" role="alert">{error}</div>:null}<ClinicalButton disabled={!postReady} loading={loading} onClick={evaluate} showArrow>محاسبه PIPP و دریافت پیشنهاد</ClinicalButton><small className="completion-note">وضعیت ورودی‌ها: {completed} مورد ثبت/تعامل شده</small>
    </div></section>
    {result?<>{result.warnings.map(warning=><div className="mismatch-warning" role={warning.blocking?'alert':'status'} key={warning.code}><AlertIcon/><span>{warning.messageFa}</span></div>)}<RecommendationPanel result={result}/>{onContinue?<div className="sticky-next"><ClinicalButton onClick={()=>onContinue(result)} showArrow>{continueLabel}</ClinicalButton></div>:null}</>:null}
  </section>
}
